---
# launch-vpc.yml
- hosts: localhost

  tasks:

    # THIS IS FAILING DUE TO UNNAMED DEPENDENCIES
    # MANUAL DELETE WORKS FINE, IT USED TO WORK, NOT
    # SURE HOW I BROKE IT
    - name: Destroy VPC
      ec2_vpc:
        region: "{{ project_region }}"
        state: absent
        cidr_block: "{{ vpc_cidr_block }}"
        resource_tags: "{{ vpc_resource_tags }}"
        internet_gateway: yes
        subnets: "{{ subnets }}"
        wait: true
      register: vpc
    - debug: msg="{{ vpc }}"
