---
- hosts: awsservers
  become: true
  tasks:
    - name: Verify Servers are Online
      local_action: wait_for host={{ inventory_hostname }} port=22
                    state=started timeout=300
      become: false

    - name: Update Servers
      yum: name=* state=latest

    - name: Reboot Servers
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      async: 1
      poll: 0
      ignore_errors: true

    - name: Wait for Servers to Reboot
      local_action: wait_for host={{ inventory_hostname }} port=22
                    state=started delay=30 timeout=300
      become: false
