---
# tasks file for httpd
- name: Install Webserver Components
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - httpd

- name: Start httpd Service
  service: name=httpd state=started enabled=yes
